#pragma once
#include <algorithm>
#include <cmath>
#include <iostream>
#include <string>
#include <array>
#include <utility>
#include <vector>
#include <memory>
#include <fstream>
#include <sstream>
#include "globals.h"
