#pragma once
#include <algorithm>
#include <iostream>
#include <string>
#include <array>
#include <vector>
#include <memory>
#include <fstream>
#include <cmath>
#include <random>
#include <SFML/Graphics.hpp>
#include "globals.h"
